import 'package:flutter/material.dart';
import 'flutter_flow/flutter_flow_util.dart';

abstract class FFAppConstants {
  static const String invoiceDownloadBaseLink =
      'http://beta.mybillions.in/platform/API/temp/invoices/';
  static const List<String> riskList = [
    'An investor with Risk Score 1 is very uncomfortable taking risks, and sees risk as leading to uncertainty and loss. As a very conservative investor, your portfolio will have primary exposure to low-volatility assets, like a basket of government bonds. Although not guaranteed, your returns should fall within a relatively narrow range; however, especially over longer timer periods, you should expect that returns will be lower than more risky portfolios.Tactical Maximum Equity Allocation will be upto 15%.',
    'An investor with Risk Score 2 is uncomfortable taking risks, and generally sees risk as uncertainty. As a conservative investor, your portfolio will have significant exposure low-volatility assets, with modest exposure to risky assets. Although not guaranteed, your returns should fall within a relatively narrow range; however, especially over longer timer periods, you should expect that returns will be lower than more risky portfolios.Tactical Maximum Equity Allocation will be upto 20%.',
    'An investor with Risk Score 3 is somewhat comfortable taking risks, and sees risk as a mix of opportunity and uncertainty. As a moderate investor, your portfolio will include investments in equities, balanced by exposure to lower-volatility assets, like a basket of government bonds. The range of potential outcomes should not be extreme, and in most cases, you should expect to outperform more conservative portfolios.Tactical Maximum Equity Allocation will be upto 40%.',
    'An investor with Risk Score 4 is comfortable taking some risks given the opportunity to assess the trade-offs. As a moderately aggressive investor, your portfolio will have greater exposure to more risky assets, like equities. You should expect some short-term fluctuations in market performance and a wider range of potential outcomes in the long-term. In most cases, and over the long term, your investments should outperform more conservative portfolios.Tactical Maximum Equity Allocation will be upto 55%.',
    'An investor with Risk Score 5 is comfortable taking risks, and sees risk as an opportunity. As an aggressive investor, your portfolio will have significant exposure to more risky assets, like equities. You should expect significant short-term fluctuations in market performance and a relatively wide range of potential outcomes in the long-term. In most cases, and over the long term, your investments should outperform more conservative portfolios.Tactical Maximum Equity Allocation will be upto 70%.',
    'An investor with Risk Score 6 is very comfortable taking risks, and sees risk as an opportunity or even a thrill. As a very aggressive investor, your portfolio will be exposed almost entirely to risky assets, such as equities. You should expect large short-term fluctuations in market performance and a very wide range of potential outcomes in the long-term. In most cases, and over the long term, your investments should outperform more conservative portfolios.Tactical Maximum Equity Allocation will be upto 100%.'
  ];
}
